def_text2img={
    "restore_faces": False,
    "face_restorer": "CodeFormer",
    "codeformer_weight": 0.5,
    "sd_model": "model.ckpt",
    "prompt": "masterpiece, high quality, full body , a girl , looking at viewer",
    "negative_prompt": "NSFW",
    "seed": "-1",
    "seed_enable_extras": False,
    "subseed": -1,
    "subseed_strength": 0,
    "seed_resize_from_h": 0,
    "seed_resize_from_w": 0,
    "sampler_name": "Euler a",
    "steps": "15",
    "cfg_scale": "5",
      "denoising_strength": 0,
    "batch_count": 1,
    "batch_size": 1,
    "base_size": 512,
    "max_size": 768,
    "tiling": False,
    "highres_fix": False,
    "firstphase_height": 512,
    "firstphase_width": 512,
    "upscaler_name": "None",
    "filter_nsfw": False,
    "include_grid": False,
    "sample_path": "outputs/krita-out",
    "orig_width": 512,
    "orig_height": 512
    }

def_img2img={
  "init_images": [
    "string"
  ],
  "prompt": "masterpiece, high quality, full body , a girl , looking at viewer",
  "resize_mode": 0,
  "denoising_strength": 0.75,
  "image_cfg_scale": 0,
  "mask": "string",
  "mask_blur": 0,
  "mask_blur_x": 4,
  "mask_blur_y": 4,
  "inpainting_fill": 0,
  "inpaint_full_res": True,
  "inpaint_full_res_padding": 0,
  "inpainting_mask_invert": 0,
  "initial_noise_multiplier": 0,
  "seed": -1,
  "subseed": -1,
  "subseed_strength": 0,
  "seed_resize_from_h": -1,
  "seed_resize_from_w": -1,
  "sampler_name": "string",
  "batch_size": 1,
  "n_iter": 1,
  "steps": 50,
  "cfg_scale": 7,
  "width": 512,
  "height": 512,
  "restore_faces": False,
  "tiling": False,
  "do_not_save_samples": False,
  "do_not_save_grid": False,
  "negative_prompt": "string",
  "eta": 0,
  "s_min_uncond": 0,
  "s_churn": 0,
  "s_tmax": 0,
  "s_tmin": 0,
  "s_noise": 1,
  "override_settings": {},
  "override_settings_restore_afterwards": True,
  "script_args": [],
  "sampler_index": "Euler",
  "include_init_images": False,
  "script_name": "string",
  "send_images": True,
  "save_images": False,
  "alwayson_scripts": {},
}